### PR TITLE
Update documentation with mysqldump backup instructions

### PR DESCRIPTION
**Pull request by GretaD**
Bug: https://phabricator.wikimedia.org/T214941

### CODE REVIEW

**Comment by GretaD** [comment]
@addshore should we kill the existing volume backup section?

**Comment by addshore** [comment]
I think this looks good.
I think we want to keep the bit about volume backups, as it makes sense for most of the services (and a general backup precaution).

Perhaps we could also add a note to the volume backup section though that says something like:

> Volume backups will only work if you use the same image when restoring / using the backup data.
> If you are backing up your mysql data you may also want to just take an SQL dump.

Thoughts?

**Comment by AlaaSarhan** [comment]
This PR seems to have issues recreating a synched branch in this repo or something. Trying to solve by reopening..

**Comment by AlaaSarhan** [comment]
hmm that failing Travis push build seems to be from an old one from a push we did mistakenly directly to this upstream, and later deleting the resulting branch on github. Think we should just ignore it, or since Travis doesn't provide a way to delete a build (afaik) the way to fix it is to rename the branch in the forked repo and open a new PR, or push to this upstream again with same branch name.

**Comment by GretaD** [comment]
we fixed the problem by stashing and pushing it again

**Pull request merged**
