### PR TITLE
Add minikube manifests, directions, and scripts

### PR DESCRIPTION
**Pull request by StevenACoffman**
This PR adds kubernetes (minikube) manifests, convenience scripts, and documentation. It should be fairly easy to adapt this for other environments (e.g. minikube on linux, windows, or kubernetes cloud providers like GKE, EKS, AKS). We are using a slightly modified version in AWS EKS for production.

### CODE REVIEW

**Comment by Ladsgroup** [comment]
I personally would love to have helm charts instead of kubernetes manifests instead. You can find examples of helm charts in https://gerrit.wikimedia.org/g/releng/local-charts

**Comment by StevenACoffman** [comment]
@Ladsgroup I don't dislike Helm or Operators, but I think plain manifests are a better starting point and make it easier to collaborate at a base level. Kubernetes by itself is already a pretty steep learning curve without introducing further concepts. A Helm chart or Operator, in addition to plain manifests, would be a good next step.

**Comment by StevenACoffman** [comment]
Closed and re-opened to retest flaky test.

**Comment by addshore** [comment]
The wikibase-docker git repository is no longer used to build the wikibase images and will no longer be maintained

Please see the announcement for new images https://lists.wikimedia.org/hyperkitty/list/wikibaseug@lists.wikimedia.org/thread/WW4LZJINT3PIG3DOYKTXIWVP3WAKWXCT/
Along with docs https://www.mediawiki.org/wiki/Wikibase/Docker

**Pull request closed without merging**
