### PR TITLE
Move general settings to separate .env file

### PR DESCRIPTION
**Pull request by SirkoS**
I tried to extract most relevant settings to a separate .env file.
In the previous version you have to manually make sure that you change a occurrences of a particular setting. Now this can be done in one file and is propagated to the respective slots in the compose file.

I do not have a proper test setup here, so I might have missed something. My manual test, however, all worked out.

PS: I'm currently working on adding the concept-URI as a new parameter, but running into some problems there. When I solve those, I'd submit another pull request.

### CODE REVIEW

**Comment by wiese** [comment]
Was there general objection about this approach (discovered myself create a similar patch, for ports in particular) or did it just fall off the radar?

**Comment by kerphi** [comment]
I think this is a good approach because it makes also possible to easily inject custom parameters thanks to local env parameters (it will then override the default .env parameters delivered by wikibase source code)

**Comment by addshore** [comment]
The docker-compose is only really meant as an example composition file and shouldn't be used directly out of this repository.
If this file is used and this repo is kept up to date (you keep pulling) there is no assurance that the file will continue working in the same way or that your services will continue working.
Really all of the README files for the individual services that are being used need to be read and understood, and services should likley be updated one at a time, not all together.

As the docker-compose is intended to be an example also including all of the settings, doing something like https://github.com/wmde/wikibase-docker/pull/91#issuecomment-542602089 starts to add a level of indirection and "magic" with things happening outside of the file.

I don't have a strong for or against stance on this PR, but perhaps we could add a note to the top of the docker-compose.yml stating that some default settings and included in the .env file?

I feel like perhaps a couple of the cars should be different too, and will comment in line!

Other than that happy to try and get this merged asap from my side.

**Comment by kerphi** [comment]
@addshore if these docker-compose.yml are dedicated for examples I agree moving parameters in .env file is not the best choice because when reading the docker-compose you don't see the parameters example easily. You have to open another file (.env) to see it, it's tedious.
It would be better (as it is now) to keep the example hard coded parameter directly into the docker-compose*.yml files. It will be more developer friendly.

So I would suggest to use this docker-compose feature: https://docs.docker.com/compose/compose-file/#variable-substitution#variable-substitution (see the default part)

Thanks to this feature, it's possible to embedded the default parameters values directly into the docker-compose.yml file. It will be the same behavior as when using a .env file but the hard coded parameters will be visible.

For example, if i consider these parameters of the .env file:
```
WB_HOST=wikibase.svc
WDQS_FRONTEND_PORT=8282
``` 

We could remove it from .env file and change where these parameters are used directly in the docker-compsoe.yml this way (example on the wdqs-frontend service):
```yaml
  wdqs-frontend:
    image: wikibase/wdqs-frontend:latest
    ports:
     - "${WDQS_FRONTEND_PORT-"8282"}:80"
    depends_on:
    - wdqs-proxy
    networks:
      default:
        aliases:
         - wdqs-frontend.svc
    environment:
      - WIKIBASE_HOST=${WB_HOST-"wikibase.svc"}
      - WDQS_HOST=wdqs-proxy.svc
```

**Comment by addshore** [comment]
That looks like quite a good compromise!
+1 lets give it a go!

It would also be nice to unify / use a naming plan for some of the environment variables as currently they are a bit all over the place. But we perhaps don't want to do that really,as that would be a breaking change (although we could add backwards compat in the entry points.

**Comment by kerphi** [comment]
@SirkoS are you ok with that?

**Comment by SirkoS** [comment]
> 
> 
> @SirkoS are you ok with that?

Sure. My main issue was that there are some settings that are repeated on multiple occasions over the file. So in my experiments I often ended up overlooking one of them or introducing typos at only one entry. So the idea behind a .env file was directed at preventing those and have a single authoritative place, where all settings are defined. Unfortunately, I dont know of a way to define env variables globally in a compose file.

As far as I understand (my compose experience is rather limited) you approach still supports having a .env to override the defaults. So I'm completely fine with that.

**Comment by addshore** [comment]
The wikibase-docker git repository is no longer used to build the wikibase images and will no longer be maintained

Please see the announcement for new images https://lists.wikimedia.org/hyperkitty/list/wikibaseug@lists.wikimedia.org/thread/WW4LZJINT3PIG3DOYKTXIWVP3WAKWXCT/
Along with docs https://www.mediawiki.org/wiki/Wikibase/Docker

If your issue still exists in the new docker images please file a task under https://phabricator.wikimedia.org/project/view/5063/

**Pull request closed without merging**
