### PR TITLE
Set quickstatements OAuth variables through reading file

### PR DESCRIPTION
**Pull request by Ladsgroup**
This makes the quickstatements service works out of the box with
no human interaction to set it up!

Bug: T205606

### CODE REVIEW

**Comment by clamor** [comment]
By now the /quickstatements/data/qs-oauth.json does not get created, probably because wikibase/1.32/bundle/extra-install.sh is stopped during elasticsearch index creation and the php command does not get executed.

As far as I can see the callback url should include the api.php in the URL, otherwise auth would not work.

Creating new items via quickstatements is not possible, probably because of missing grants? I do not know whether this is intended or not.

**Comment by Ladsgroup** [comment]
I don't understand the issue right now, I was able to build and run the docker containers using docker-compose. Travis also successfully built and ran them. The fix for elastic search should be up by now.

**Comment by clamor** [comment]
Building runs fine, the problem occurs when instantiating the containers and the extra-install.sh script is executed. You will see the errors below and the containers get started but qs-oauth.json will not be created.

wikibase_1         | indexing namespaces...
elasticsearch_1    | [2019-02-26T10:15:53,180][WARN ][o.e.i.r.TransportDeleteByQueryAction] [Nl3nt6Q] giving up on search because it failed with a non-retryable exception
elasticsearch_1    | org.elasticsearch.index.IndexNotFoundException: no such index
elasticsearch_1    | 	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.infe(IndexNameExpressionResolver.java:678) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.innerResolve(IndexNameExpressionResolver.java:632) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver.resolve(IndexNameExpressionResolver.java:580) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:169) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:141) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.action.search.TransportSearchAction.executeSearch(TransportSearchAction.java:265) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:188) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:67) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:170) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:142) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:84) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:83) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:72) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:67) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.client.ParentTaskAssigningClient.doExecute(ParentTaskAssigningClient.java:66) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.client.support.AbstractClient.search(AbstractClient.java:535) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.index.reindex.ClientScrollableHitSource.lambda$doStart$0(ClientScrollableHitSource.java:81) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.index.reindex.ClientScrollableHitSource$1RetryHelper.doRun(ClientScrollableHitSource.java:146) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.index.reindex.ClientScrollableHitSource.searchWithRetry(ClientScrollableHitSource.java:178) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.index.reindex.ClientScrollableHitSource.doStart(ClientScrollableHitSource.java:81) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.index.reindex.ScrollableHitSource.start(ScrollableHitSource.java:69) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.index.reindex.AbstractAsyncBulkByScrollAction.start(AbstractAsyncBulkByScrollAction.java:259) ~[?:?]
elasticsearch_1    | 	at org.elasticsearch.index.reindex.TransportDeleteByQueryAction.doExecute(TransportDeleteByQueryAction.java:61) ~[?:?]
elasticsearch_1    | 	at org.elasticsearch.index.reindex.TransportDeleteByQueryAction.doExecute(TransportDeleteByQueryAction.java:37) ~[?:?]
elasticsearch_1    | 	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:170) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:142) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:84) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:83) ~[elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.index.reindex.AbstractBaseReindexRestHandler.lambda$doPrepareRequest$0(AbstractBaseReindexRestHandler.java:62) ~[?:?]
elasticsearch_1    | 	at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:80) [elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:262) [elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:200) [elasticsearch-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.http.netty4.Netty4HttpServerTransport.dispatchRequest(Netty4HttpServerTransport.java:505) [transport-netty4-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:80) [transport-netty4-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at org.elasticsearch.http.netty4.pipelining.HttpPipeliningHandler.channelRead(HttpPipeliningHandler.java:68) [transport-netty4-5.6.9.jar:5.6.9]
elasticsearch_1    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [netty-codec-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-codec-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [netty-codec-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.13.Final.jar:4.1.13.Final]
elasticsearch_1    | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
wikibase_1         | [5131603d6605453ed554762d] [no req]   Elastica\Exception\ResponseException from line 179 of /var/www/html/extensions/Elastica/vendor/ruflin/elastica/lib/Elastica/Transport/Http.php: no such index [index: mw_cirrus_metastore]
wikibase_1         | Backtrace:
wikibase_1         | #0 /var/www/html/extensions/Elastica/vendor/ruflin/elastica/lib/Elastica/Request.php(193): Elastica\Transport\Http->exec(Elastica\Request, array)
wikibase_1         | #1 /var/www/html/extensions/Elastica/vendor/ruflin/elastica/lib/Elastica/Client.php(674): Elastica\Request->send()
wikibase_1         | #2 /var/www/html/extensions/Elastica/vendor/ruflin/elastica/lib/Elastica/Client.php(706): Elastica\Client->request(string, string, array, array)
wikibase_1         | #3 /var/www/html/extensions/Elastica/vendor/ruflin/elastica/lib/Elastica/Index.php(562): Elastica\Client->requestEndpoint(Elasticsearch\Endpoints\DeleteByQuery)
wikibase_1         | #4 /var/www/html/extensions/Elastica/vendor/ruflin/elastica/lib/Elastica/Type.php(523): Elastica\Index->requestEndpoint(Elasticsearch\Endpoints\DeleteByQuery)
wikibase_1         | #5 /var/www/html/extensions/Elastica/vendor/ruflin/elastica/lib/Elastica/Type.php(491): Elastica\Type->requestEndpoint(Elasticsearch\Endpoints\DeleteByQuery)
wikibase_1         | #6 /var/www/html/extensions/CirrusSearch/includes/MetaStore/MetaNamespaceStore.php(65): Elastica\Type->deleteByQuery(Elastica\Query)
wikibase_1         | #7 /var/www/html/extensions/CirrusSearch/maintenance/indexNamespaces.php(39): CirrusSearch\MetaStore\MetaNamespaceStore->reindex(LanguageEn)
wikibase_1         | #8 /var/www/html/extensions/CirrusSearch/maintenance/updateSearchIndexConfig.php(57): CirrusSearch\Maintenance\IndexNamespaces->execute()
wikibase_1         | #9 /var/www/html/maintenance/doMaintenance.php(94): CirrusSearch\Maintenance\UpdateSearchIndexConfig->execute()
wikibase_1         | #10 /var/www/html/extensions/CirrusSearch/maintenance/updateSearchIndexConfig.php(73): require_once(string)
wikibase_1         | #11 {main}
wikibase_1         | 	Indexing namespaces...wikibase-docker_wikibase_1 exited with code 255

**Comment by clamor** [comment]
The fixes to Elastica und CirrusSearch are finally up.

To get elasticsearch running, a wikibase specific plugin has to be installed to elasticsearch. That plugin is not available for the current elasticsearch version used in the docker compose files. So I replaced it with a custom elasticsearch docker image:

FROM elasticsearch:5.6.14
RUN ./bin/elasticsearch-plugin install org.wikimedia.search:extra:5.6.14

Now instantiating and configuring elasticsearch works and /quickstatements/data/qs-oauth.json gets created.

**Comment by clamor** [comment]
A last one:

the /var/www/html/extensions/OAuth/maintenance/createOAuthConsumer.php command seems to recognize only the first value of the --grants parameter. The following seem to be ignored.

**Comment by Ladsgroup** [comment]
> A last one:
> 
> the /var/www/html/extensions/OAuth/maintenance/createOAuthConsumer.php command seems to recognize only the first value of the --grants parameter. The following seem to be ignored.

Thanks for catching it. I put up #71 for that.

**Comment by AlaaSarhan** [comment]
+1

I tried to test it locally, but due to some weird docker stuff I couldn't make it just work.. I'll leave it to some Docker wizard to check and merge

**Comment by addshore** [comment]
> The fixes to Elastica und CirrusSearch are finally up.
> 
> To get elasticsearch running, a wikibase specific plugin has to be installed to elasticsearch. That plugin is not available for the current elasticsearch version used in the docker compose files. So I replaced it with a custom elasticsearch docker image:
> 
> FROM elasticsearch:5.6.14
> RUN ./bin/elasticsearch-plugin install org.wikimedia.search:extra:5.6.14
> 
> Now instantiating and configuring elasticsearch works and /quickstatements/data/qs-oauth.json gets created.

It sounds like we still need to tackle this.
@clamor any chance of a PR? :)

**Comment by AlaaSarhan** [comment]
elastic search use case will be handled in https://phabricator.wikimedia.org/T217344

@addshore do we wait on merging for that ticket?

**Comment by addshore** [comment]
I don't think we need to wait.
This quickstatements image works independently to the mediawiki / elasticsearch image.
In theory people can use any number of combinations of these images.
So lets merge this if it is ready!

**Pull request merged**
