### PR TITLE
Make mediawiki build a OAuth consumer for quickstatements 

### PR DESCRIPTION
**Pull request by Ladsgroup**
and share it with quickstatements.

Bug: T205606

### CODE REVIEW

**Comment by Ladsgroup** [comment]
The failure is unrelated and fixable by #67

**Comment by addshore** [comment]
I just clicked restart build to see if this now passes :)

**Comment by Ladsgroup** [comment]
> I just clicked restart build to see if this now passes :)

So the push one fails because the PR is not rebased against master but since pr tests pass, I think it's fine.

**Comment by addshore** [comment]
I think the readme also needs updating
https://github.com/wmde/wikibase-docker/blob/master/quickstatements/README.md

**Comment by Ladsgroup** [comment]
> Readme needs updating https://github.com/wmde/wikibase-docker/blob/master/quickstatements/README.md

Done

**Pull request merged**
