### PR TITLE
Fixed username in the QuickStatement "token" generation

### PR DESCRIPTION
**Pull request by manicki**
Apparently got forgotten in https://github.com/wmde/wikibase-docker/pull/86/commits/531fbda7ab5fc96dcbe5e1c5a5b300859d5773e0 / https://github.com/wmde/wikibase-docker/pull/86

### CODE REVIEW

**Comment by manicki** [comment]
Do not merge. CI should be fixed first

**Comment by manicki** [comment]
Looks the CI failures are inconsistent (test jobs failing at different stages), will look more into them tomorrow

**Comment by manicki** [comment]
CI build intended to be fixed by https://github.com/wmde/wikibase-docker/pull/93.

**Comment by Ladsgroup** [comment]
The push fails because it's not rebased on top of master. Meh.

**Pull request merged**
